# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Fee Test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'IGListKit', '~> 4.0.0'
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'Alamofire', '~> 5.0.0-rc.3'

  target 'Fee TestTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
